INC=/usr/include
MLX_DIR=..

all: $(MLX_DIR)/libmlx.a $(NAME)

$(MLX_DIR)/libmlx.a:
	$(MAKE) -C $(MLX_DIR)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJ) $(LFLAGS)

.PHONY: clean fclean re

clean:
	$(RM) -f *.o *.out a.out $(NAME)
	$(RM) -rf *.dSYM

fclean: clean

re: fclean all
